default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("DB_HOST", "db") %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "password") %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "ballast_development") %>

test:
  <<: *default
  database: ballast_test

production:
  <<: *default
  database: ballast_production
  url: <%= ENV["DATABASE_URL"] %>
